### ISSUE TITLE
Empty CSS file

### ISSUE THREAD

**Issue by davestewart** [rawcreative/vueify-extract-css#1]
Hello.

Just tried this in a vanilla gulp setup, but I get an empty CSS file, and vueify's style tag is still attached to the document's head.

**Comment by rawcreative** [comment]
What version of Vueify are you using? Also, can you provide a snippet of how you're calling the plugin in your gulpfile?

**Comment by davestewart** [comment]
Hey Tim, thanks for responding!

Looks like version 0.1.0.

Here's my setup:

``` js
gulp.task('vueify', function ()
{
    // paths
    var src = './../resources/assets/test/main.js';
    var trg = '../public/assets/js/';

    // browserify
    return browserify({
        paths: ['./node_modules/'],
        entries:src
    })

    // transform
    .transform(babelify, { presets: [es2015], plugins: [txRuntime] })
    .transform(vueify)
    .plugin(cssExtract, { out: 'bundle.css' })
    .bundle()

    // compress
    .pipe(source('bundle.js'))
    .pipe(buffer())
    .pipe(uglify())

    // output
    .pipe(gulp.dest(trg));
});
```

The string method doesn't always work for me, so I require and pass plugins directly.

**Comment by davestewart** [comment]
So in my setup, the plugin seems to return here:

https://github.com/rawcreative/vueify-extract-css/blob/master/index.js#L42

It's as if vueify-insert-css hasn't run. It's not being called as far as I can tell.

I plonked some code into the `extract()` function in to scan for `<style>` and none were found either.

Am I right in supposing that this plugin is supposed to extract the compiled contents of all style tags and stick them in a single output CSS file?

**Comment by rawcreative** [comment]
Looks like this commit from a couple weeks ago: https://github.com/vuejs/vueify/commit/2fb82818d44499aea64cd7a7978006abda10941c modified how the styles are inserted, which is why it's not finding any styles. I've got a working fix for it but want to test it a little more before I push it.

**Comment by davestewart** [comment]
That's reassuring! I'm a recent immigrant into this Brave New World of ES6 + build processes, so glad I'm not barking up the wrong (Abstract Syntax) Tree. Looking forward to it.

**Comment by rawcreative** [comment]
Fixed in https://github.com/rawcreative/vueify-extract-css/commit/306afd6d8ec4d8e2f9af211833cbcabc174e5992

**Comment by davestewart** [comment]
Great stuff, thanks!

**Comment by davestewart** [comment]
OK, have updated to 0.2.0 but still getting empty CSS output.

The text '[vueify](https://github.com/vuejs/vueify/commit/2fb82818d44499aea64cd7a7978006abda10941c)' is not being found at all in `extract()`. 

```
console.log('>>>>>>>>>>>>>>>>>>>>>', chunk.source.indexOf('vueify'));
```

Am I fundamentally misunderstanding what this plugin does?

**Comment by rawcreative** [comment]
Hmm, I'm not really sure.. I just tested it on two different projects using the current release of vueify and it's extracting the css as intended.

Can you post one of your  single file .vue components?

**Comment by davestewart** [comment]
Ah... it is working!

To put your mind at rest - I hadn't yet added any CSS to my components, but I was importing Vue Strap which was adding a boatload of style tags to the page.

Your extension is firing for each of them (I assume, per-component), but isn't extracting anything. 

There seems to be [some kind of compilation issue](https://github.com/yuche/vue-strap/issues/55#issuecomment-199189792) with VueStrap so the workaround is to do this:

```
var Modal = require('vue-strap/dist/vue-strap.min').modal;
```

I guess being minified, your plugin is not going to pick up on that.

Anyway, not your problem! 

Thanks for the fix.

**Comment by rawcreative** [comment]
The problem is likely due to the fact that the VueStrap components you linked are compiled with Webpack, not Browserify. So the whole mechanism for inserting styles onto the page is different. Since you're also pulling in the dist/precompiled versions, browserify isn't actually inserting any css which is why you're not seeing anything extracted. You would have to be using the non-compiled versions of the components to be able to pull out the css.

**Comment by davestewart** [comment]
That makes sense.

And unfortunately the original VueStrap files cause Vueify to bork immediately on importing with this rubbish:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at EventEmitter.compiler.applyConfig (/Volumes/Data/Work/Current/2015-07 - Timeslice, Kiosk 3.0/timeslice.kiosk/support/node_modules/vueify/lib/compiler.js:52:10)
    at vueify (/Volumes/Data/Work/Current/2015-07 - Timeslice, Kiosk 3.0/timeslice.kiosk/support/node_modules/vueify/index.js:8:12)
...
```

Have since decided to include all libs as external resources anyway, so no need to bloat my build :)

**Comment by mediafreakch** [comment]
@rawcreative Is `0.2.0` still compatible with `vueify 9.4.0`? Or can it be that the insert syntax changed? I'm getting empty files too...

**Comment by mediafreakch** [comment]
I just found that as from vueify `9.x` you need to use `vueify/plugins/extract-css` instead of `vueify-extract-css`. An example can be found in the [vueify readme](https://github.com/vuejs/vueify#css-extraction)
